### PR TITLE
Fixes location duplication

### PR DESCRIPTION
**Pull request by andrechalom**
This branch includes some decisions that I'm not very sure about, so I'd like to have some opinions. If you both are able, please test the functionality in this branch, particularly creating and exporting Locations, and let me know what you think. If you need some help in using the branch system or setting up the tests, let me know!

### CODE REVIEW

**Comment by birutaibm** [comment]
I having a problem during installation process. It does not occurs if I try to install for the master branch. But when I use `git checkout fix190` and them `php install` I see the error:
```
Running database migrations... This may take a while...
Migration table created successfully.

In Model.php line 23:
                                              
  No query results for model [App\Location].  
                                              

running 'php artisan migrate' failed!
```
Both installations (master and fix190 branches) was made after delete the previous folder of opendatabio and clone it again, and after drop database opendatabio.
Any idea?

**Comment by andrechalom** [comment]
Found out the error. It's an incompatibility between the global scope used to "hide" the World object, and the Baum library, which manages the hierarquical relations in the Location and Taxon tables. This is... very unfortunate. I'll have to rewrite the scope...

**Comment by birutaibm** [comment]
During the installation I choose generate seed and get another error:
```
Seeding: PlantsTableSeeder

In Arr.php line 480:
                                                                
  You requested 1 items, but there are only 0 items available.  
                                                                

running 'php artisan db:seed' failed!
```
Installing by the master branch this error don't occurs.
I try to install one more time by the fix190 branch and the error remains.

**Comment by birutaibm** [comment]
I install without the seeds to do other tests. At the web interface for localities, when click the button to create a new one, it gives me the error `BadMethodCallException: Method noWorld does not exist.` It looks like laravel needs noWord in the global scope. :(

**Comment by andrechalom** [comment]
Thanks for all the tests... I'll fix these two problems still today, both
were caused by typos / small oversights.

**Comment by birutaibm** [comment]
Ok. I will wait for your next commit to do more tests.

**Comment by andrechalom** [comment]
Sorry for the delay, my computer broke down last weeend, I expect to have
it fixed by tuesday.

**Comment by andrechalom** [comment]
Fixes finally applied! If everything goes well, we can merge this.

**Comment by birutaibm** [comment]
Yet another error...
At the installation process, I choose to generate seed, then it ends with this messages:
```
Seeding: VouchersTableSeeder
Seeding: TraitsTableSeeder

In Connection.php line 664:
                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Ap  
  p\ODBTrait-28-0' for key 'user_translations_language_translatable_unique' (  
  SQL: insert into `user_translations` (`translatable_id`, `translatable_type  
  `, `language_id`, `translation_type`, `translation`, `updated_at`, `created  
  _at`) values (28, App\ODBTrait, 1, 0, Fertility by Reinger's method, 2018-0  
  3-01 11:05:52, 2018-03-01 11:05:52))                                         
                                                                               

In Connection.php line 458:
                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Ap  
  p\ODBTrait-28-0' for key 'user_translations_language_translatable_unique'    
                                                                               

running 'php artisan db:seed' failed!
```
Note that this is not at the process of seed location!

Then, I try to access the web interface (as other user) and get another error:
`The stream or file "/home/odbserver/opendatabio/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied`
Checking the permissions I see:
```
$ ls -la /home/odbserver/opendatabio/storage/logs/laravel.log
-rw-rw-r-- 1 odbserver odbserver 9789 Mar  1 08:05 /home/odbserver/opendatabio/storage/logs/laravel.log
```
It seems like the odbserver have the appropriate permissions, right?

**Comment by birutaibm** [comment]
Once that the seed generation fails, I uninstall and them install without generate seed. At the web interface I successfully create one location. Then, I go to url `http://localhost/opendatabio/api/v0/locations?limite=0` when I expect to see only the metadata of the response (without any registry) but I obtain `{"meta":{"odb_version":"0.7.4","api_version":"v0","server":"http:\/\/localhost\/opendatabio","full_url":"http:\/\/localhost\/opendatabio\/api\/v0\/locations?limite=0"},"data":[{"id":2,"name":"Biruta Country","geom":"POLYGON((10 10,50 10,50 50,10 50,10 10),(20 20,30 20,30 30,20 30,20 20))","levelName":"Country"}]}`.

Note that I do not check if this issue is specific of this branch or if the master is returning the same response. Can anybody check the response at a master branch installation and move this comment to a new issue if this is the case?

**Comment by andrechalom** [comment]
Actually, none of these errors seem related to the modifications in this
branch. The first one seems to indicate that the same trait is receiving a
name twice (ODBTrait-28-0 means this is a translation for the trait id 28
from the language 0, which I believe is english?). Can you check that the
user_translations table is empty when the seed proccess starts?

The second problem, permissions, is because the user running the Apache
server also needs write permission to this file. The install script should
grant write permission to all users in the log directory, please check
again after a successful php install.

Finally, I believe the third issue is a typo, can you check using "limit"
instead of "limite"?

On Mar 1, 2018 08:29, "birutaibm" <notifications@github.com> wrote:

Yet another error...
At the installation process, I choose to generate seed, then it ends with
this messages:

Seeding: VouchersTableSeeder
Seeding: TraitsTableSeeder

In Connection.php line 664:

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Ap
  p\ODBTrait-28-0' for key 'user_translations_language_translatable_unique' (
  SQL: insert into `user_translations` (`translatable_id`, `translatable_type
  `, `language_id`, `translation_type`, `translation`, `updated_at`, `created
  _at`) values (28, App\ODBTrait, 1, 0, Fertility by Reinger's method, 2018-0
  3-01 11:05:52, 2018-03-01 11:05:52))


In Connection.php line 458:

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Ap
  p\ODBTrait-28-0' for key 'user_translations_language_translatable_unique'


running 'php artisan db:seed' failed!

Note that this is not at the process of seed location!

Then, I try to access the web interface (as other user) and get another
error:
The stream or file "/home/odbserver/opendatabio/storage/logs/laravel.log"
could not be opened: failed to open stream: Permission denied
Checking the permissions I see:

$ ls -la /home/odbserver/opendatabio/storage/logs/laravel.log
-rw-rw-r-- 1 odbserver odbserver 9789 Mar  1 08:05
/home/odbserver/opendatabio/storage/logs/laravel.log

It seems like the odbserver have the appropriate permissions, right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/opendatabio/opendatabio/pull/191#issuecomment-369563199>,
or mute the thread

**Comment by birutaibm** [comment]
Yes, it was a typo, I am sorry. So I correct it, but I have the same result. Then I check the source code and I understand, it tests `if (limit)` to apply the limit but php understand 0 as false and then do not apply the limit. Reflecting about this issue, I think it was a stupid test (if I need only metadata, I need to use "test" instead of "get locations" with limit=0). So I delete my comment here and edit the wiki to say that limit must be greater than 0.

About the first error, the database was empty, because it was created at the installation process (I delete the previous version with `mysql -u root -p opendatabio -e "drop database if exists opendatabio"` before install. I will try install again...

**Pull request merged**
